server:
  port: 9888
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
logging:
  level:
    org.springframework.jdbc.core: TRACE
spring:
  profiles:
    group:
      dev:
        - "infra-dev"
        - "dev"
      prod:
        - "infra-prod"
        - "prod"
    active: "${profile}"
    include: "infra"
my: "\${server.port}"
